apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deploy
  labels:
    app: platformservices
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: platformservices
  template:
    metadata:
      labels:
        app: platformservices
    spec:
      containers:
        - name: platformservices
          image: evaldoavelar/platformservices:1.1
          imagePullPolicy: Never
          ports:
          - containerPort: 80