### variables are defined at settings.json file inside .vscode
### Ctrl+Alt+e to change the environment

GET http://localhost:30593/api/platforms HTTP/1.1

###
GET http://localhost:80/api/platforms HTTP/1.1

###

GET {{host}}/api/platforms/1 HTTP/1.1

###

POST {{host}}/api/platforms HTTP/1.1
content-type: application/json

{    
    "name": "Delphi",
    "published": "Embarcadero",
    "cost": "$ 5000"
  }
